on:
  push:
    branches:
      - test
 
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.TEST_ACCESS_KEY  }}
      AWS_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY  }}
 
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
 
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.2
 
    - name: Terraform Init
      run: terraform init
 
    - name: Terraform Plan
      run: terraform plan
 
    - name: Terraform Apply
      run: terraform apply -auto-approve
